# Setup
title:            'Organ Donation in America'
tagline:          'Investigating the roadblocks in a broken system'
description:      'This is the description'

author:
  name:           'Author'
  url:            https://github.com/CTOpenData/data-sharing-playbook

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/CTOpenData/data-sharing-playbook

# Google Analytics
google_analytics: UA-XXXXXXXXXX-X

plugins:
  - jekyll-toc

toc:
  min_level: 2 # default: 1
  max_level: 2 # default: 6
